#server:
# port: '8082'


#spring:
#  h2:
 #   console:
  # datasource:
   # username: sa
    #url: jdbc:h2:mem:testdb
    ##password: password
 # jpa:
  #  database-platform: org.hibernate.dialect.H2Dialect
#welcome:
#  message: Welcome to Spring-Boot Application..!!!
  


